Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network  "forwarded_port", guest:80, host: 8089 # NAT
    # config.vm.network "private_network", ip: "192.168.50.4" # Host-only
    # config.vm.network "private_network", type: "dhcp" # Host-only
    config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3168", ip: "192.168.0.30" # bridged
  end